# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install texlive-xetex latexmk libpng-dev libjpeg-dev libtiff-dev imagemagick -y
        python -m pip install --upgrade pip
        python -m pip install ghp-import
        npm install -g mystmd
    #   if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Manually download docx template
      run: |
        cd docs
        wget https://github.com/myst-templates/docx_default/archive/refs/heads/main.zip
        mkdir -p _build/templates/docx/myst/default
        unzip main.zip -d _build/templates/docx/myst/default  
        cp _build/templates/docx/myst/default/docx_default-main/styles.xml _build/templates/docx/myst/default/styles.xml

    - name: Build docs with MySt
      run: |
        cd docs 
        myst build -a
        ghp-import -n -p -f _build/site
        cd ..
        mv docs /tmp/.
        
    - name: Commit files
      run: |
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"    
        git fetch origin
        git branch -a
        git checkout -b myst origin/myst
        git pull
        rm -rf docs
        mv /tmp/docs .
        git add --all
        git commit -a -m "autogen"
        git remote set-url origin https://spisakt:${{ secrets.GIT_TOKEN }}@github.com/pni-lab/connattractor.git
        git push origin myst
