# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        npm install -g myst-cli
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Build docs with MySt
      run: |
        cd docs 
        myst build -a
    - name: GitHub Pages
      uses: crazy-max/ghaction-github-pages@v3.1.0
      with:
        # Build directory to deploy
        build_dir: docs/_build
        jekyll: false # optional, default is true
        # If enabled, nothing will be pushed
        dry_run: false # optional, default is false
        # Enable verbose output
        verbose: true # optional, default is false
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

